# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test_base.json --output_file output/deepseek_coder-v2-q8_base.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8_base.log 2> logs/deepseek_coder-v2-q8_base.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test_block.json --output_file output/deepseek_coder-v2-q8_block.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8_block.log 2> logs/deepseek_coder-v2-q8_block.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test_cotblock.json --output_file output/deepseek_coder-v2-q8_cotblock.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8_cotblock.log 2> logs/deepseek_coder-v2-q8_cotblock.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test_cotfewblock.json --output_file output/deepseek_coder-v2-q8_cotfewblock.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8_cotfewblock.log 2> logs/deepseek_coder-v2-q8_cotfewblock.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test_cotfew.json --output_file output/deepseek_coder-v2-q8_cotfew.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8_cotfew.log 2> logs/deepseek_coder-v2-q8_cotfew.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test_cot.json --output_file output/deepseek_coder-v2-q8_cot.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8_cot.log 2> logs/deepseek_coder-v2-q8_cot.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test_fewshot.json --output_file output/deepseek_coder-v2-q8_fewshot.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8_fewshot.log 2> logs/deepseek_coder-v2-q8_fewshot.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test_fsblock.json --output_file output/deepseek_coder-v2-q8_fsblock.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8_fsblock.log 2> logs/deepseek_coder-v2-q8_fsblock.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test.json --output_file output/deepseek_coder-v2-q8.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-q8.log 2> logs/deepseek_coder-v2-q8.log < /dev/null &
# python run_score.py --input_file output/deepseek_coder-v2-q8_base.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8_base.json
python run_score.py --input_file output/deepseek_coder-v2-q8_block.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8_block.json
python run_score.py --input_file output/deepseek_coder-v2-q8_cotblock.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8_cotblock.json
python run_score.py --input_file output/deepseek_coder-v2-q8_cotfewblock.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8_cotfewblock.json
python run_score.py --input_file output/deepseek_coder-v2-q8_cotfew.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8_cotfew.json
python run_score.py --input_file output/deepseek_coder-v2-q8_cot.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8_cot.json
python run_score.py --input_file output/deepseek_coder-v2-q8_fewshot.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8_fewshot.json
python run_score.py --input_file output/deepseek_coder-v2-q8_fsblock.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8_fsblock.json
python run_score.py --input_file output/deepseek_coder-v2-q8.json --source_names C,C++,C#,Java,Go,PHP,Python,VB --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/deepseek_coder-v2-q8.json
