# python run_translation_api.py --input_file data/preprocessed_multilingual_test.json --output_file output/o3-mini.json --dotenv_path /home/kobashi/code_llm_evaluations/.env --platform OpenAI --model o3-mini
python run_score.py --input_file output/o3-mini.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/o3-mini.json
# python run_translation_api.py --input_file data/preprocessed_multilingual_test.json --output_file output/o1-mini.json --dotenv_path /home/kobashi/code_llm_evaluations/.env --platform OpenAI --model o1-mini
python run_score.py --input_file output/o1-mini.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/o1-mini.json
# python run_translation_api.py --input_file data/preprocessed_multilingual_test.json --output_file output/gpt-4o.json --dotenv_path /home/kobashi/code_llm_evaluations/.env --platform OpenAI --model gpt-4o
python run_score.py --input_file output/gpt-4o.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/gpt-4o.json
# python run_translation_api.py --input_file data/preprocessed_multilingual_test.json --output_file output/gemini-2.0-flash-thinking-exp.json --dotenv_path /home/kobashi/code_llm_evaluations/.env --platform Google --model gemini-2.0-flash-thinking-exp --delay 5
python run_score.py --input_file output/gemini-2.0-flash-thinking-exp.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/gemini-2.0-flash-thinking-exp.json
# python run_translation_api.py --input_file data/preprocessed_multilingual_test.json --output_file output/gemini-2.0-flash.json --dotenv_path /home/kobashi/code_llm_evaluations/.env --platform Google --model gemini-2.0-flash
python run_score.py --input_file output/gemini-2.0-flash.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/gemini-2.0-flash.json
# python run_translation_api.py --input_file data/preprocessed_multilingual_test.json --output_file output/claude-3-7-sonnet-20250219.json --dotenv_path /home/kobashi/code_llm_evaluations/.env --platform Anthropic --model claude-3-7-sonnet-20250219
python run_score.py --input_file output/claude-3-7-sonnet-20250219.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/claude-3-7-sonnet-20250219.json
python run_translation_api.py --input_file data/preprocessed_multilingual_test.json --output_file output/claude-3-7-sonnet-20250219_reasoning.json --dotenv_path /home/kobashi/code_llm_evaluations/.env --platform Anthropic --model claude-3-7-sonnet-20250219 --reasoning
python run_score.py --input_file output/claude-3-7-sonnet-20250219_reasoning.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/claude-3-7-sonnet-20250219.json
python run_translation_api.py --input_file data/preprocessed_multilingual_test.json --output_file output/claude-3-5-haiku-20241022.json --dotenv_path /home/kobashi/code_llm_evaluations/.env --platform Anthropic --model claude-3-5-haiku-20241022
python run_score.py --input_file output/claude-3-5-haiku-20241022.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --output_file scores/claude-3-5-haiku-20241022.json
python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test.json --output_file output/deepseek-coder-v2-lite-instruct.json
python run_translation_deepseek_coder.py --input_file data/preprocessed_multilingual_test.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf --output_file output/deepseek-coder-v2-lite-instruct-Q8_0.json