# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans_base.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans_base.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans_base.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans_base.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans_block.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans_block.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans_block.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans_block.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans_cotblock.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans_cotblock.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans_cotblock.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans_cotblock.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans_cotfewblock.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans_cotfewblock.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans_cotfewblock.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans_cotfewblock.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans_cotfew.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans_cotfew.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans_cotfew.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans_cotfew.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans_cot.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans_cot.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans_cot.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans_cot.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans_fewshot.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans_fewshot.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans_fewshot.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans_fewshot.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans_fsblock.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans_fsblock.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans_fsblock.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans_fsblock.log < /dev/null &
# nohup python run_translation_deepseek_coder.py --input_file data/preprocessed_LLMTrans.json --output_file output/deepseek_coder-v2-Q8_0_llmtrans.json --gguf_path models/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf > logs/deepseek_coder-v2-Q8_0_llmtrans.log 2> logs/deepseek_coder-v2-Q8_0_llmtrans.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans_base.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans_base.json > logs/score-v2-Q8_0_llmtrans_base.log 2> logs/score-v2-Q8_0_llmtrans_base.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans_block.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans_block.json > logs/score-v2-Q8_0_llmtrans_block.log 2> logs/score-v2-Q8_0_llmtrans_block.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans_cotblock.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans_cotblock.json > logs/score-v2-Q8_0_llmtrans_cotblock.log 2> logs/score-v2-Q8_0_llmtrans_cotblock.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans_cotfewblock.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans_cotfewblock.json > logs/score-v2-Q8_0_llmtrans_cotfewblock.log 2> logs/score-v2-Q8_0_llmtrans_cotfewblock.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans_cotfew.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans_cotfew.json > logs/score-v2-Q8_0_llmtrans_cotfew.log 2> logs/score-v2-Q8_0_llmtrans_cotfew.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans_cot.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans_cot.json > logs/score-v2-Q8_0_llmtrans_cot.log 2> logs/score-v2-Q8_0_llmtrans_cot.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans_fewshot.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans_fewshot.json > logs/score-v2-Q8_0_llmtrans_fewshot.log 2> logs/score-v2-Q8_0_llmtrans_fewshot.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans_fsblock.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans_fsblock.json > logs/score-v2-Q8_0_llmtrans_fsblock.log 2> logs/score-v2-Q8_0_llmtrans_fsblock.log < /dev/null &
nohup python run_score.py --input_file output/deepseek_coder-v2-Q8_0_llmtrans.json --source_names C,C++,C#,Java,Go,PHP,Python,VB  --target_names C,C++,C#,Java,Go,PHP,Python,VB --codebleu --execute --output_file scores/deepseek_coder-v2-Q8_0_llmtrans.json > logs/score-v2-Q8_0_llmtrans.log 2> logs/score-v2-Q8_0_llmtrans.log < /dev/null &
